# Generated by Django 2.0.4 on 2018-05-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ag_evo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.PositiveSmallIntegerField()),
                ('change', models.NullBooleanField(default=False)),
                ('breed', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ag',
            name='change',
        ),
        migrations.AddField(
            model_name='ag_evo',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Ag'),
        ),
    ]
